version: '2.1'
services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar 
      - POSTGRES_PASSWORD=sonar 
      - POSTGRE_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always
  sonarqube:
    image: sonarqube:7.1
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://127.0.0.1:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
    restart: always
